# Generated by Django 5.1.7 on 2025-03-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.PositiveIntegerField(),
        ),
    ]
